export const FETCH_PRODUCT='FETCH_PRODUCT';
export const ADD_TO_CART='ADD_TO_CART';
export const DELETE_TO_CART='DELETE_TO_CART';
export const UPDATE_QUANTITY='UPDATE_QUANTITY';
export const FETCH_PRODUCT_CATEGORY='FETCH_PRODUCT_CATEGORY';
export const SEARCH_PRODUCT='SEARCH_PRODUCT';